name: currency_scanner
description: "A Flutter app for detecting counterfeit currency"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2           # Downgraded to match Flutter SDK pinning
  provider: ^6.1.1
  camera: ^0.11.0
  permission_handler: ^11.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_vision: ^2.0.0
  ultralytics_yolo: ^0.0.1
  tflite_flutter: ^0.12.1
  image: ^4.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: 1.1.3
  build_runner: 2.3.3

flutter:
  uses-material-design: true
  generate: true    
  assets:
    - assets/logo.jpg
    - assets/models/best_float32.tflite
    - assets/models/labels.txt
    - assets/models/verifier.tflite
    - assets/models/verifier_labels.txt
